name: concordile

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: concordile-db
      POSTGRES_USER: concordile-user
      POSTGRES_PASSWORD: concordile-pass
    ports:
      - 5432:5432
