apiVersion: v1
kind: ConfigMap
metadata:
  name: c8e-broker-cm
  namespace: c8e
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-svc:5432/${DB_NAME}
  SPRING_DATASOURCE_USERNAME: ${DB_USER}
  SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
