server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: concordile-broker
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: 'update'
