GET http://localhost:8080/api/v1/producers
Accept: application/json

###

GET http://localhost:8080/api/v1/producers/producer-service
Accept: application/json

###

GET http://localhost:8080/api/v1/producers/producer-service/consumers
Accept: application/json

###
