name: Image workflow

on:
  push:
    branches:
      - image

permissions:
  contents: read
  packages: write

jobs:
  image:
    name: Image job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage --publishImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DOCKER_REGISTRY: ghcr.io
          GITHUB_DOCKER_URL: https://ghcr.io
