name: Image workflow

permissions:
  contents: read
  packages: write

jobs:
  image:
    name: Image job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build image
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootBuildImage
        env:
          GITHUB_DOCKER_REGISTRY: ghcr.io
