name: Image workflow

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  image:
    name: Image job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build by gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DOCKER_REGISTRY: ghcr.io
          GITHUB_DOCKER_URL: https://ghcr.io
        run: gradle bootBuildImage

      - name: Push to ghcr.io
        run: docker push ghcr.io/concordile/concordile-broker:0.1.0-SNAPSHOT

      - name: Login to docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create tag for docker.io
        run: docker tag ghcr.io/concordile/concordile-broker:0.1.0-SNAPSHOT docker.io/concordile/concordile-broker:0.1.0-SNAPSHOT

      - name: Push to docker.io
        run: docker push docker.io/concordile/concordile-broker:0.1.0-SNAPSHOT
